/**
 * Next.js configuration
 * Proxy auth service under the same origin during development.
 */
import path from 'path';
import { existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';
import { spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';

const require = createRequire(import.meta.url);
const __dirname = path.dirname(fileURLToPath(import.meta.url));

function getSerwistRevision() {
  try {
    const stdout = spawnSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf-8' }).stdout?.trim();
    if (stdout) return stdout.slice(0, 12);
  } catch {
    // ignore — not a git repo or git unavailable
  }
  return randomUUID();
}

/** Optional — dev Docker volumes may lag package.json until `npm install` runs. */
function loadSerwistWrapper() {
  try {
    const withSerwistInit = require('@serwist/next').default;
    return withSerwistInit({
      swSrc: 'src/sw.ts',
      swDest: 'public/sw.js',
      cacheOnNavigation: true,
      reloadOnOnline: true,
      disable: process.env.NODE_ENV === 'development' && process.env.NEXT_PUBLIC_PWA_DEV !== 'true',
      additionalPrecacheEntries: [{ url: '/offline', revision: getSerwistRevision() }],
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.warn(`[PWA] @serwist/next unavailable — skipping service worker wrapper (${message})`);
    return (config) => config;
  }
}

const withSerwist = loadSerwistWrapper();

function loadSentryWrapper() {
  try {
    return require('@sentry/nextjs').withSentryConfig;
  } catch {
    return null;
  }
}

// Webpack alias: @/ee → ee/src/ee/ (EE) or src/ee-fallback.ts (CE).
// Turbopack: does not support absolute-path aliases; resolution handled by the
// src/ee/index.ts shim generated by scripts/setup-ee.js at container startup.
const eeIndex    = path.resolve(__dirname, 'ee/src/ee/index.ts');
const eeFallback = path.resolve(__dirname, 'src/ee-fallback.ts');
const pricingModalNoop = path.resolve(__dirname, 'src/components/PricingModal.noop.tsx');
const edition = (process.env.NEXT_PUBLIC_EDITION || process.env.EDITION || '').toLowerCase();
const isEnterprise = edition === 'enterprise' || edition === 'ee';
const eeEntry    = isEnterprise && existsSync(eeIndex) ? path.dirname(eeIndex) : eeFallback;

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Avoid failing builds due to ESLint plugin issues in CI/dev images
  eslint: {
    ignoreDuringBuilds: true,
  },

  typescript: {
    ignoreBuildErrors: true,
  },

  output: 'standalone',

  productionBrowserSourceMaps: false,

  experimental: {
    webpackBuildWorker: false,
    ...(process.env.NEXT_DEV_CPUS
      ? { cpus: Number.parseInt(process.env.NEXT_DEV_CPUS, 10) }
      : {}),
    workerThreads: false,
    optimizePackageImports: ['antd', '@ant-design/icons', 'echarts'],
    instrumentationHook: true,
    turbo: {
      resolveAlias: {
        // Note: @/ee is NOT aliased here — Turbopack does not support absolute-path aliases.
        // Resolution is handled by the src/ee/index.ts shim generated by scripts/setup-ee.js,
        // which uses a relative import (../../ee/src/ee) that Turbopack supports.
        'antd/es/typography/Base/Ellipsis': './src/patches/antd-safe-ellipsis.tsx',
        'antd/es/typography/Base/Ellipsis.js': './src/patches/antd-safe-ellipsis.tsx',
        'antd/lib/typography/Base/Ellipsis': './src/patches/antd-safe-ellipsis.tsx',
        'antd/lib/typography/Base/Ellipsis.js': './src/patches/antd-safe-ellipsis.tsx',
      },
    },
  },

  webpack: (config, { isServer }) => {
    // Limit webpack's internal module parallelism to reduce peak heap usage
    config.parallelism = 1;

    config.resolve.extensionAlias = {
      '.js': ['.js', '.ts', '.tsx'],
      '.jsx': ['.jsx', '.tsx'],
    };
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      // CE/EE build-time swap — no runtime decision, no symlinks
      '@/ee': eeEntry,
      ...(!isEnterprise
        ? { '@/ee/components/PricingModal': pricingModalNoop }
        : {}),
      // Ant Design ellipsis patch
      'antd/es/typography/Base/Ellipsis': path.resolve(process.cwd(), 'src/patches/antd-safe-ellipsis.tsx'),
      'antd/es/typography/Base/Ellipsis.js': path.resolve(process.cwd(), 'src/patches/antd-safe-ellipsis.tsx'),
      'antd/lib/typography/Base/Ellipsis': path.resolve(process.cwd(), 'src/patches/antd-safe-ellipsis.tsx'),
      'antd/lib/typography/Base/Ellipsis.js': path.resolve(process.cwd(), 'src/patches/antd-safe-ellipsis.tsx'),
    };

    if (!isServer) {
      config.resolve.fallback = {
        ...config.resolve.fallback,
        fs: false,
        net: false,
        tls: false,
      };

      // Force the browser-only Sentry bundle in client chunks.
      // Without this, webpack falls through to the "import" condition which
      // resolves to index.server.js and pulls in Node.js OpenTelemetry
      // instrumentation (~50 MB), bloating the client build and exhausting
      // the dev-server heap.
      try {
        config.resolve.alias['@sentry/nextjs'] = require.resolve(
          '@sentry/nextjs/build/cjs/index.client.js',
        );
      } catch {
        // @sentry/nextjs not installed — no-op
      }
    }

    return config;
  },
};

const sentryEnabled = Boolean(
  process.env.NEXT_PUBLIC_SENTRY_DSN || process.env.SENTRY_DSN,
);
const withSentryConfig = sentryEnabled ? loadSentryWrapper() : null;

export default withSerwist(
  withSentryConfig
    ? withSentryConfig(nextConfig, {
        silent: true,
        org: process.env.SENTRY_ORG,
        project: process.env.SENTRY_PROJECT,
        authToken: process.env.SENTRY_AUTH_TOKEN,
        widenClientFileUpload: true,
      })
    : nextConfig,
);
