/**
 * Next.js configuration
 * Proxy auth service under the same origin during development.
 */
import path from 'path';
import { existsSync } from 'fs';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Webpack alias: @/ee → ee/src/ee/ (EE) or src/ee-fallback.ts (CE).
// Turbopack: does not support absolute-path aliases; resolution handled by the
// src/ee/index.ts shim generated by scripts/setup-ee.js at container startup.
const eeIndex    = path.resolve(__dirname, 'ee/src/ee/index.ts');
const eeFallback = path.resolve(__dirname, 'src/ee-fallback.ts');
const edition = (process.env.NEXT_PUBLIC_EDITION || process.env.EDITION || '').toLowerCase();
const isEnterprise = edition === 'enterprise' || edition === 'ee';
const eeEntry    = isEnterprise && existsSync(eeIndex) ? path.dirname(eeIndex) : eeFallback;

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Avoid failing builds due to ESLint plugin issues in CI/dev images
  eslint: {
    ignoreDuringBuilds: true,
  },

  typescript: {
    ignoreBuildErrors: true,
  },

  output: 'standalone',

  experimental: {
    optimizePackageImports: ['antd', '@ant-design/icons', 'echarts'],
    turbo: {
      resolveAlias: {
        // Note: @/ee is NOT aliased here — Turbopack does not support absolute-path aliases.
        // Resolution is handled by the src/ee/index.ts shim generated by scripts/setup-ee.js,
        // which uses a relative import (../../ee/src/ee) that Turbopack supports.
        'antd/es/typography/Base/Ellipsis': './src/patches/antd-safe-ellipsis.tsx',
        'antd/es/typography/Base/Ellipsis.js': './src/patches/antd-safe-ellipsis.tsx',
        'antd/lib/typography/Base/Ellipsis': './src/patches/antd-safe-ellipsis.tsx',
        'antd/lib/typography/Base/Ellipsis.js': './src/patches/antd-safe-ellipsis.tsx',
      },
    },
  },

  webpack: (config, { isServer }) => {
    config.resolve.extensionAlias = {
      '.js': ['.js', '.ts', '.tsx'],
      '.jsx': ['.jsx', '.tsx'],
    };
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      // CE/EE build-time swap — no runtime decision, no symlinks
      '@/ee': eeEntry,
      // Ant Design ellipsis patch
      'antd/es/typography/Base/Ellipsis': path.resolve(process.cwd(), 'src/patches/antd-safe-ellipsis.tsx'),
      'antd/es/typography/Base/Ellipsis.js': path.resolve(process.cwd(), 'src/patches/antd-safe-ellipsis.tsx'),
      'antd/lib/typography/Base/Ellipsis': path.resolve(process.cwd(), 'src/patches/antd-safe-ellipsis.tsx'),
      'antd/lib/typography/Base/Ellipsis.js': path.resolve(process.cwd(), 'src/patches/antd-safe-ellipsis.tsx'),
    };

    if (!isServer) {
      config.resolve.fallback = {
        ...config.resolve.fallback,
        fs: false,
        net: false,
        tls: false,
      };
    }

    return config;
  },
};

export default nextConfig;
