/**
 * Generates src/ee shims at startup so EE modules resolve for both webpack and Turbopack.
 *
 * Turbopack follows the @/* → src/* tsconfig wildcard before checking resolveAlias,
 * so it finds src/ee/ first. Having a real index.ts there (pointing to the right barrel)
 * makes resolution work without requiring Turbopack alias overrides.
 *
 * webpack: resolveAlias override takes precedence regardless, so this file is harmless.
 */

const { existsSync, writeFileSync, mkdirSync } = require('fs');
const path = require('path');

function writeShim(filePath, content) {
  const body = Array.isArray(content) ? content.join('\n') : content;
  try {
    writeFileSync(filePath, body);
  } catch (err) {
    if (err && err.code === 'EACCES') {
      const fixScript = path.resolve(__dirname, '../../scripts/fix-docker-permissions.sh');
      console.error(
        `[setup-ee] Cannot write ${filePath}: permission denied.\n` +
          `This usually happens after Docker dev created root/nobody-owned files.\n` +
          `Fix ownership, then re-run postinstall:\n` +
          `  sudo ${fixScript}\n` +
          `  npm run postinstall`
      );
      process.exit(1);
    }
    throw err;
  }
}

const root       = path.resolve(__dirname, '..');
const eeIndex    = path.join(root, 'ee', 'src', 'ee', 'index.ts');
const eeShimDir  = path.join(root, 'src', 'ee');
const eeShimFile = path.join(eeShimDir, 'index.ts');
const eeChatPage = path.join(root, 'ee', 'src', 'ee', 'app', '(dashboard)', 'chat', 'page.tsx');
const eeChatShimFile = path.join(eeShimDir, 'chat-page.tsx');

mkdirSync(eeShimDir, { recursive: true });

const edition = (
  process.env.NEXT_PUBLIC_EDITION ||
  process.env.EDITION ||
  process.env.AISER_EDITION ||
  ''
).toLowerCase();
const isEnterprise = edition === 'enterprise' || edition === 'ee';
const hasEnterpriseModules = existsSync(eeIndex) && existsSync(eeChatPage);

// Prefer file-presence detection: if the EE submodule is checked out the shim
// should point to it regardless of whether env vars are loaded yet (e.g. predev
// runs before Next.js reads .env). Env-var check is kept as a fallback for
// cases where the submodule is absent but CI still needs EE mode.
if (hasEnterpriseModules || isEnterprise) {
  writeShim(
    eeShimFile,
    [
      '// Auto-generated by scripts/setup-ee.js — do not edit manually.',
      "// EE submodule present: re-exports the real EE barrel.",
      "export * from '../../ee/src/ee/index';",
      '',
    ]
  );
  writeShim(
    eeChatShimFile,
    [
      '// Auto-generated by scripts/setup-ee.js — do not edit manually.',
      "export { default } from '../../ee/src/ee/app/(dashboard)/chat/page';",
      '',
    ]
  );
  console.log('[setup-ee] EE mode — generated EE module shims');
} else {
  writeShim(
    eeShimFile,
    [
      '// Auto-generated by scripts/setup-ee.js — do not edit manually.',
      "// EE submodule absent or CE edition: re-exports CE null stubs.",
      "export * from '../ee-fallback';",
      '',
    ]
  );
  writeShim(
    eeChatShimFile,
    [
      '// Auto-generated by scripts/setup-ee.js — do not edit manually.',
      "export { default } from '../ee-chat-page-fallback';",
      '',
    ]
  );
  console.log('[setup-ee] CE mode — generated CE fallback shims');
}
