/**
 * Generates src/ee/index.ts at startup so @/ee resolves for both webpack and Turbopack.
 *
 * Turbopack follows the @/* → src/* tsconfig wildcard before checking resolveAlias,
 * so it finds src/ee/ first. Having a real index.ts there (pointing to the right barrel)
 * makes resolution work without requiring Turbopack alias overrides.
 *
 * webpack: resolveAlias override takes precedence regardless, so this file is harmless.
 */

const { existsSync, writeFileSync, mkdirSync } = require('fs');
const path = require('path');

const root       = path.resolve(__dirname, '..');
const eeIndex    = path.join(root, 'ee', 'src', 'ee', 'index.ts');
const eeShimDir  = path.join(root, 'src', 'ee');
const eeShimFile = path.join(eeShimDir, 'index.ts');

mkdirSync(eeShimDir, { recursive: true });

const edition = (process.env.EDITION || process.env.NEXT_PUBLIC_EDITION || '').toLowerCase();
const isEnterprise = edition === 'enterprise' || edition === 'ee';

if (isEnterprise && existsSync(eeIndex)) {
  writeFileSync(
    eeShimFile,
    [
      '// Auto-generated by scripts/setup-ee.js — do not edit manually.',
      "// EE submodule present: re-exports the real EE barrel.",
      "export * from '../../ee/src/ee/index';",
      '',
    ].join('\n')
  );
  console.log('[setup-ee] EE mode — src/ee/index.ts → ee/src/ee');
} else {
  writeFileSync(
    eeShimFile,
    [
      '// Auto-generated by scripts/setup-ee.js — do not edit manually.',
      "// EE submodule absent or CE edition: re-exports CE null stubs.",
      "export * from '../ee-fallback';",
      '',
    ].join('\n')
  );
  console.log('[setup-ee] CE mode — src/ee/index.ts → ee-fallback');
}
