name: aiser-ee-self-host-local

services:
  postgres:
    container_name: aiser-postgres-ee-self-host-local
    ports: !override
      - "${SELF_HOST_POSTGRES_PORT_HOST:-5435}:5432"

  redis:
    container_name: aiser-redis-ee-self-host-local

  server:
    image: ${AISER_SERVER_IMAGE:-aiser-ee-server:self-host}
    container_name: aiser-server-ee-self-host-local
    environment:
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3100}
    ports: !override
      - "${SELF_HOST_SERVER_PORT_HOST:-8100}:8000"

  client:
    image: ${AISER_CLIENT_IMAGE:-aiser-ee-client:self-host}
    container_name: aiser-client-ee-self-host-local
    ports: !override
      - "${SELF_HOST_CLIENT_PORT_HOST:-3100}:3000"

volumes:
  postgres_ee_data:
    name: aiser_postgres_ee_self_host_local_data
  redis_ee_data:
    name: aiser_redis_ee_self_host_local_data
  server_ee_uploads:
    name: aiser_server_ee_self_host_local_uploads

networks:
  default:
    name: aiser-ee-self-host-local-network
