"""initial

Revision ID: 27d6aeac1832
Revises: 
Create Date: 2026-04-29 08:30:26.565766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d6aeac1832'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charts_id'), table_name='charts')
    op.create_index(op.f('ix_charts_id'), 'charts', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charts_id'), table_name='charts')
    op.create_index(op.f('ix_charts_id'), 'charts', ['id'], unique=False)
    # ### end Alembic commands ###