"""ee_tables

Revision ID: f11a9f2c63b1
Revises: 0079d06b6fed
Create Date: 2026-04-29 09:54:19.612005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f11a9f2c63b1'
down_revision: Union[str, None] = '0079d06b6fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_charts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('chart_id', sa.UUID(), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_charts_chart_id'), 'dashboard_charts', ['chart_id'], unique=False)
    op.create_index(op.f('ix_dashboard_charts_dashboard_id'), 'dashboard_charts', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_charts_id'), 'dashboard_charts', ['id'], unique=False)
    op.create_table('dashboard_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('template_config', sa.JSON(), nullable=False),
    sa.Column('preview_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('required_plan', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('natural_language_query', sa.Text(), nullable=True),
    sa.Column('query_config', sa.JSON(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('query_type', sa.JSON(), nullable=True),
    sa.Column('business_context', sa.JSON(), nullable=True),
    sa.Column('chart_type', sa.String(), nullable=True),
    sa.Column('chart_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_queries_id'), 'data_queries', ['id'], unique=False)
    op.create_index(op.f('ix_data_queries_user_id'), 'data_queries', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('telegram_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action', 'resource', name='uq_permission_action_resource'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.Enum('organization', 'project', name='role_scope_enum'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'scope', name='uq_role_name_scope')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('schema_column_index',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_column_index_column_name'), 'schema_column_index', ['column_name'], unique=False)
    op.create_index(op.f('ix_schema_column_index_data_source_id'), 'schema_column_index', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_schema_column_index_id'), 'schema_column_index', ['id'], unique=False)
    op.create_index(op.f('ix_schema_column_index_table_name'), 'schema_column_index', ['table_name'], unique=False)
    op.create_table('schema_table_index',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.Column('column_names_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('column_types_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domain_tag', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_table_index_data_source_id'), 'schema_table_index', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_schema_table_index_domain_tag'), 'schema_table_index', ['domain_tag'], unique=False)
    op.create_index(op.f('ix_schema_table_index_id'), 'schema_table_index', ['id'], unique=False)
    op.create_index(op.f('ix_schema_table_index_table_name'), 'schema_table_index', ['table_name'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=64), server_default=sa.text("'user'"), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=True),
    sa.Column('tenant_id', sa.String(length=128), server_default=sa.text("'default'"), nullable=True),
    sa.Column('onboarding_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('is_pro', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('job_role', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('data_experience', sa.String(length=50), nullable=True),
    sa.Column('primary_use_case', sa.String(length=100), nullable=True),
    sa.Column('data_frequency', sa.String(length=50), nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('telegram_status', sa.Enum('connected', 'pending', 'disconnected', name='telegram_status_enum'), nullable=True),
    sa.Column('telegram_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('dashboard_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('load_time', sa.Float(), nullable=True),
    sa.Column('render_time', sa.Float(), nullable=True),
    sa.Column('query_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_embeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('embed_token', sa.String(length=255), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('page_order', sa.Integer(), nullable=True),
    sa.Column('layout_config', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('shared_with', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('share_token', sa.String(length=255), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_author_follows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_feed_author_follow')
    )
    op.create_index('idx_feed_author_follows_follower', 'feed_author_follows', ['follower_id'], unique=False)
    op.create_index('idx_feed_author_follows_following', 'feed_author_follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_feed_author_follows_id'), 'feed_author_follows', ['id'], unique=False)
    op.create_table('organization_invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', 'revoked', name='invite_status_enum'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'organization_id', 'status', name='uq_active_invite_per_email_org')
    )
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_id'), 'organization_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_token'), 'organization_invitations', ['token'], unique=True)
    op.create_table('organization_kpi_definitions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('kpi_slug', sa.String(length=100), nullable=False),
    sa.Column('kpi_name', sa.String(length=200), nullable=False),
    sa.Column('trigger_keywords', sa.Text(), server_default='', nullable=False),
    sa.Column('sql_expression', sa.Text(), nullable=False),
    sa.Column('required_tables', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('data_source_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'kpi_slug', name='uq_org_kpi_slug')
    )
    op.create_index('ix_org_kpi_org_id', 'organization_kpi_definitions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_kpi_definitions_id'), 'organization_kpi_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_organization_kpi_definitions_organization_id'), 'organization_kpi_definitions', ['organization_id'], unique=False)
    op.create_table('organization_subscriptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'canceled', name='subscription_status_enum'), server_default=sa.text("'trialing'"), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_expiring_soon', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_subscription', 'organization_subscriptions', ['provider', 'provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_id'), 'organization_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_organization_id'), 'organization_subscriptions', ['organization_id'], unique=True)
    op.create_index(op.f('ix_organization_subscriptions_plan_id'), 'organization_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_provider'), 'organization_subscriptions', ['provider'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_provider_customer_id'), 'organization_subscriptions', ['provider_customer_id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_provider_subscription_id'), 'organization_subscriptions', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_status'), 'organization_subscriptions', ['status'], unique=False)
    op.create_table('organization_usage',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'metric', 'period_start', name='uq_org_metric_period')
    )
    op.create_index('idx_org_usage_lookup', 'organization_usage', ['organization_id', 'metric', 'period_end'], unique=False)
    op.create_index(op.f('ix_organization_usage_id'), 'organization_usage', ['id'], unique=False)
    op.create_index(op.f('ix_organization_usage_metric'), 'organization_usage', ['metric'], unique=False)
    op.create_index(op.f('ix_organization_usage_organization_id'), 'organization_usage', ['organization_id'], unique=False)
    op.create_table('payment_history',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('provider_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_transaction', 'payment_history', ['provider', 'provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_payment_history_id'), 'payment_history', ['id'], unique=False)
    op.create_index(op.f('ix_payment_history_organization_id'), 'payment_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payment_history_provider'), 'payment_history', ['provider'], unique=False)
    op.create_index(op.f('ix_payment_history_provider_invoice_id'), 'payment_history', ['provider_invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_history_provider_transaction_id'), 'payment_history', ['provider_transaction_id'], unique=False)
    op.create_index('uq_payment_provider_invoice_id', 'payment_history', ['provider_invoice_id'], unique=True, postgresql_where=sa.text('provider_invoice_id IS NOT NULL'))
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('query_patterns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('data_source_id', sa.String(), nullable=True),
    sa.Column('schema_hash', sa.String(length=24), nullable=False),
    sa.Column('nl_query', sa.Text(), nullable=False),
    sa.Column('nl_query_normalized', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('analytics_type', sa.String(length=50), server_default=sa.text("'descriptive'"), nullable=True),
    sa.Column('score', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('execution_count', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=50), server_default=sa.text("'ai_pipeline'"), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('dashboard_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_patterns_data_source_id'), 'query_patterns', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_query_patterns_id'), 'query_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_query_patterns_nl_query_normalized'), 'query_patterns', ['nl_query_normalized'], unique=False)
    op.create_index(op.f('ix_query_patterns_schema_hash'), 'query_patterns', ['schema_hash'], unique=False)
    op.create_index(op.f('ix_query_patterns_user_id'), 'query_patterns', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', 'id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('scheduled_emails',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('to_emails', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('time_of_day', sa.String(length=5), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.Enum('ONCE', 'DAILY', 'WEEKLY', 'MONTHLY', name='scheduletype'), nullable=False),
    sa.Column('next_send_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_emails_id'), 'scheduled_emails', ['id'], unique=False)
    op.create_table('catalog_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('freshness_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'asset_type', 'source_ref', name='uq_catalog_asset_project_type_ref')
    )
    op.create_index(op.f('ix_catalog_assets_asset_type'), 'catalog_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_catalog_assets_id'), 'catalog_assets', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_assets_owner_user_id'), 'catalog_assets', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_catalog_assets_project_id'), 'catalog_assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_catalog_assets_source_ref'), 'catalog_assets', ['source_ref'], unique=False)
    op.create_table('connector_runtime_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('connector_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_runtime_jobs_connector_mode'), 'connector_runtime_jobs', ['connector_mode'], unique=False)
    op.create_index(op.f('ix_connector_runtime_jobs_id'), 'connector_runtime_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_connector_runtime_jobs_project_id'), 'connector_runtime_jobs', ['project_id'], unique=False)
    op.create_table('conversation',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=True),
    sa.Column('type', sa.String(length=50), server_default=sa.text("'chat2chart'"), nullable=True),
    sa.Column('json_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_id'), 'conversation', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_project_id'), 'conversation', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('db_type', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('sample_data', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connection_config', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.String(), server_default=sa.text("'default'"), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_user_id'), 'data_sources', ['user_id'], unique=False)
    op.create_table('feed_collections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_collections_id'), 'feed_collections', ['id'], unique=False)
    op.create_table('feed_posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_type', sa.Enum('dashboard', 'chart', 'insight', name='asset_type_enum'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'project', 'organization', 'public', name='feed_visibility_enum'), server_default=sa.text("'private'"), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'rejected', name='publish_status_enum'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.UUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('featured_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_access_level', sa.Enum('results_only', 'full_access', name='publication_access_level_enum'), server_default=sa.text("'results_only'"), nullable=False),
    sa.Column('requires_login', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reaction_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('save_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('share_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type', 'asset_id', name='uq_feed_posts_asset')
    )
    op.create_index('idx_feed_posts_org_visibility', 'feed_posts', ['organization_id', 'visibility'], unique=False)
    op.create_index('idx_feed_posts_project_visibility', 'feed_posts', ['project_id', 'visibility'], unique=False)
    op.create_index(op.f('ix_feed_posts_id'), 'feed_posts', ['id'], unique=False)
    op.create_table('file_storage',
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('file_data', postgresql.BYTEA(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('object_key')
    )
    op.create_index(op.f('ix_file_storage_object_key'), 'file_storage', ['object_key'], unique=False)
    op.create_table('platform_lineage_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('data_source_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_lineage_events_actor_user_id'), 'platform_lineage_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_platform_lineage_events_created_at'), 'platform_lineage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_lineage_events_data_source_id'), 'platform_lineage_events', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_platform_lineage_events_event_type'), 'platform_lineage_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_platform_lineage_events_id'), 'platform_lineage_events', ['id'], unique=False)
    op.create_index(op.f('ix_platform_lineage_events_project_id'), 'platform_lineage_events', ['project_id'], unique=False)
    op.create_table('platform_policy_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=64), server_default=sa.text("'data_access'"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_policy_rules_id'), 'platform_policy_rules', ['id'], unique=False)
    op.create_index(op.f('ix_platform_policy_rules_project_id'), 'platform_policy_rules', ['project_id'], unique=False)
    op.create_table('project_data_source',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('data_source_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_data_source_data_source_id'), 'project_data_source', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_project_data_source_id'), 'project_data_source', ['id'], unique=False)
    op.create_index(op.f('ix_project_data_source_project_id'), 'project_data_source', ['project_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'organization_id', 'project_id', name='uq_user_role_assignment')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('charts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('chart_type', sa.String(length=100), nullable=True),
    sa.Column('chart_query', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('chart_options', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('chart_library', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('complexity_score', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=255), nullable=True),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datasource', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charts_data_source_id'), 'charts', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_charts_id'), 'charts', ['id'], unique=True)
    op.create_index(op.f('ix_charts_user_id'), 'charts', ['user_id'], unique=False)
    op.create_table('feed_collection_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['feed_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'post_id', name='uq_feed_collection_item')
    )
    op.create_index(op.f('ix_feed_collection_items_id'), 'feed_collection_items', ['id'], unique=False)
    op.create_table('feed_comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mentions', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('moderation_status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['feed_comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_comments_id'), 'feed_comments', ['id'], unique=False)
    op.create_table('feed_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('publish', 'comment', 'reaction', 'approval', 'share', 'save', 'mention', 'created', 'updated', 'approved', 'rejected', 'approval_requested', name='event_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_events_id'), 'feed_events', ['id'], unique=False)
    op.create_table('feed_interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('like', 'love', 'insightful', 'applause', 'funny', 'celebrate', 'save', name='interaction_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', 'type', name='uq_feed_interactions_user_type')
    )
    op.create_index(op.f('ix_feed_interactions_id'), 'feed_interactions', ['id'], unique=False)
    op.create_table('feed_shares',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_shares_id'), 'feed_shares', ['id'], unique=False)
    op.create_table('feed_views',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_views_id'), 'feed_views', ['id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'processing'"), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_data_source_id'), 'knowledge_documents', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_user_id'), 'knowledge_documents', ['user_id'], unique=False)
    op.create_table('llm_audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('data_source_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('analysis_mode', sa.String(length=64), nullable=True),
    sa.Column('node_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('valid_output', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_audit_log_data_source_id'), 'llm_audit_log', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_llm_audit_log_id'), 'llm_audit_log', ['id'], unique=False)
    op.create_index('ix_llm_audit_log_org_created', 'llm_audit_log', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_audit_log_organization_id'), 'llm_audit_log', ['organization_id'], unique=False)
    op.create_index(op.f('ix_llm_audit_log_project_id'), 'llm_audit_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_llm_audit_log_provider'), 'llm_audit_log', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_audit_log_request_id'), 'llm_audit_log', ['request_id'], unique=False)
    op.create_table('llm_request_summary',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('data_source_id', sa.String(), nullable=True),
    sa.Column('total_prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_completion_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dataset_size_mb', sa.Float(), nullable=True),
    sa.Column('estimated_credits', sa.Integer(), nullable=True),
    sa.Column('credits_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('real_cost_usd', sa.String(length=20), nullable=True),
    sa.Column('final_status', sa.String(length=20), nullable=True),
    sa.Column('total_attempts', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_request_summary_data_source_id'), 'llm_request_summary', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_llm_request_summary_id'), 'llm_request_summary', ['id'], unique=False)
    op.create_index('ix_llm_request_summary_org_created', 'llm_request_summary', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_request_summary_organization_id'), 'llm_request_summary', ['organization_id'], unique=False)
    op.create_index(op.f('ix_llm_request_summary_project_id'), 'llm_request_summary', ['project_id'], unique=False)
    op.create_index(op.f('ix_llm_request_summary_request_id'), 'llm_request_summary', ['request_id'], unique=True)
    op.create_table('message',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_user_id'), 'message', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_data_source_id'), 'document_chunks', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('feed_comment_reactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction', sa.Enum('like', 'love', 'insightful', 'applause', 'funny', 'celebrate', name='comment_reaction_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['feed_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_feed_comment_reaction_user')
    )
    op.create_index('idx_feed_comment_reactions_comment', 'feed_comment_reactions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_feed_comment_reactions_id'), 'feed_comment_reactions', ['id'], unique=False)
    op.create_table('feed_notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('mention', 'comment', 'reaction', 'share', 'approval', name='notification_type_enum'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['feed_comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_notifications_id'), 'feed_notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_notifications_id'), table_name='feed_notifications')
    op.drop_table('feed_notifications')
    op.drop_index(op.f('ix_feed_comment_reactions_id'), table_name='feed_comment_reactions')
    op.drop_index('idx_feed_comment_reactions_comment', table_name='feed_comment_reactions')
    op.drop_table('feed_comment_reactions')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_data_source_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_message_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_llm_request_summary_request_id'), table_name='llm_request_summary')
    op.drop_index(op.f('ix_llm_request_summary_project_id'), table_name='llm_request_summary')
    op.drop_index(op.f('ix_llm_request_summary_organization_id'), table_name='llm_request_summary')
    op.drop_index('ix_llm_request_summary_org_created', table_name='llm_request_summary')
    op.drop_index(op.f('ix_llm_request_summary_id'), table_name='llm_request_summary')
    op.drop_index(op.f('ix_llm_request_summary_data_source_id'), table_name='llm_request_summary')
    op.drop_table('llm_request_summary')
    op.drop_index(op.f('ix_llm_audit_log_request_id'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_llm_audit_log_provider'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_llm_audit_log_project_id'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_llm_audit_log_organization_id'), table_name='llm_audit_log')
    op.drop_index('ix_llm_audit_log_org_created', table_name='llm_audit_log')
    op.drop_index(op.f('ix_llm_audit_log_id'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_llm_audit_log_data_source_id'), table_name='llm_audit_log')
    op.drop_table('llm_audit_log')
    op.drop_index(op.f('ix_knowledge_documents_user_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_data_source_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_feed_views_id'), table_name='feed_views')
    op.drop_table('feed_views')
    op.drop_index(op.f('ix_feed_shares_id'), table_name='feed_shares')
    op.drop_table('feed_shares')
    op.drop_index(op.f('ix_feed_interactions_id'), table_name='feed_interactions')
    op.drop_table('feed_interactions')
    op.drop_index(op.f('ix_feed_events_id'), table_name='feed_events')
    op.drop_table('feed_events')
    op.drop_index(op.f('ix_feed_comments_id'), table_name='feed_comments')
    op.drop_table('feed_comments')
    op.drop_index(op.f('ix_feed_collection_items_id'), table_name='feed_collection_items')
    op.drop_table('feed_collection_items')
    op.drop_index(op.f('ix_charts_user_id'), table_name='charts')
    op.drop_index(op.f('ix_charts_id'), table_name='charts')
    op.drop_index(op.f('ix_charts_data_source_id'), table_name='charts')
    op.drop_table('charts')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_project_data_source_project_id'), table_name='project_data_source')
    op.drop_index(op.f('ix_project_data_source_id'), table_name='project_data_source')
    op.drop_index(op.f('ix_project_data_source_data_source_id'), table_name='project_data_source')
    op.drop_table('project_data_source')
    op.drop_index(op.f('ix_platform_policy_rules_project_id'), table_name='platform_policy_rules')
    op.drop_index(op.f('ix_platform_policy_rules_id'), table_name='platform_policy_rules')
    op.drop_table('platform_policy_rules')
    op.drop_index(op.f('ix_platform_lineage_events_project_id'), table_name='platform_lineage_events')
    op.drop_index(op.f('ix_platform_lineage_events_id'), table_name='platform_lineage_events')
    op.drop_index(op.f('ix_platform_lineage_events_event_type'), table_name='platform_lineage_events')
    op.drop_index(op.f('ix_platform_lineage_events_data_source_id'), table_name='platform_lineage_events')
    op.drop_index(op.f('ix_platform_lineage_events_created_at'), table_name='platform_lineage_events')
    op.drop_index(op.f('ix_platform_lineage_events_actor_user_id'), table_name='platform_lineage_events')
    op.drop_table('platform_lineage_events')
    op.drop_index(op.f('ix_file_storage_object_key'), table_name='file_storage')
    op.drop_table('file_storage')
    op.drop_index(op.f('ix_feed_posts_id'), table_name='feed_posts')
    op.drop_index('idx_feed_posts_project_visibility', table_name='feed_posts')
    op.drop_index('idx_feed_posts_org_visibility', table_name='feed_posts')
    op.drop_table('feed_posts')
    op.drop_index(op.f('ix_feed_collections_id'), table_name='feed_collections')
    op.drop_table('feed_collections')
    op.drop_index(op.f('ix_data_sources_user_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_project_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_connector_runtime_jobs_project_id'), table_name='connector_runtime_jobs')
    op.drop_index(op.f('ix_connector_runtime_jobs_id'), table_name='connector_runtime_jobs')
    op.drop_index(op.f('ix_connector_runtime_jobs_connector_mode'), table_name='connector_runtime_jobs')
    op.drop_table('connector_runtime_jobs')
    op.drop_index(op.f('ix_catalog_assets_source_ref'), table_name='catalog_assets')
    op.drop_index(op.f('ix_catalog_assets_project_id'), table_name='catalog_assets')
    op.drop_index(op.f('ix_catalog_assets_owner_user_id'), table_name='catalog_assets')
    op.drop_index(op.f('ix_catalog_assets_id'), table_name='catalog_assets')
    op.drop_index(op.f('ix_catalog_assets_asset_type'), table_name='catalog_assets')
    op.drop_table('catalog_assets')
    op.drop_index(op.f('ix_scheduled_emails_id'), table_name='scheduled_emails')
    op.drop_table('scheduled_emails')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_query_patterns_user_id'), table_name='query_patterns')
    op.drop_index(op.f('ix_query_patterns_schema_hash'), table_name='query_patterns')
    op.drop_index(op.f('ix_query_patterns_nl_query_normalized'), table_name='query_patterns')
    op.drop_index(op.f('ix_query_patterns_id'), table_name='query_patterns')
    op.drop_index(op.f('ix_query_patterns_data_source_id'), table_name='query_patterns')
    op.drop_table('query_patterns')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('uq_payment_provider_invoice_id', table_name='payment_history', postgresql_where=sa.text('provider_invoice_id IS NOT NULL'))
    op.drop_index(op.f('ix_payment_history_provider_transaction_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_provider_invoice_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_provider'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_organization_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_id'), table_name='payment_history')
    op.drop_index('idx_provider_transaction', table_name='payment_history')
    op.drop_table('payment_history')
    op.drop_index(op.f('ix_organization_usage_organization_id'), table_name='organization_usage')
    op.drop_index(op.f('ix_organization_usage_metric'), table_name='organization_usage')
    op.drop_index(op.f('ix_organization_usage_id'), table_name='organization_usage')
    op.drop_index('idx_org_usage_lookup', table_name='organization_usage')
    op.drop_table('organization_usage')
    op.drop_index(op.f('ix_organization_subscriptions_status'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_provider_subscription_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_provider_customer_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_provider'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_plan_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_organization_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_id'), table_name='organization_subscriptions')
    op.drop_index('idx_provider_subscription', table_name='organization_subscriptions')
    op.drop_table('organization_subscriptions')
    op.drop_index(op.f('ix_organization_kpi_definitions_organization_id'), table_name='organization_kpi_definitions')
    op.drop_index(op.f('ix_organization_kpi_definitions_id'), table_name='organization_kpi_definitions')
    op.drop_index('ix_org_kpi_org_id', table_name='organization_kpi_definitions')
    op.drop_table('organization_kpi_definitions')
    op.drop_index(op.f('ix_organization_invitations_token'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_email'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_feed_author_follows_id'), table_name='feed_author_follows')
    op.drop_index('idx_feed_author_follows_following', table_name='feed_author_follows')
    op.drop_index('idx_feed_author_follows_follower', table_name='feed_author_follows')
    op.drop_table('feed_author_follows')
    op.drop_table('dashboard_shares')
    op.drop_table('dashboard_pages')
    op.drop_table('dashboard_embeds')
    op.drop_table('dashboard_analytics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_slug'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_schema_table_index_table_name'), table_name='schema_table_index')
    op.drop_index(op.f('ix_schema_table_index_id'), table_name='schema_table_index')
    op.drop_index(op.f('ix_schema_table_index_domain_tag'), table_name='schema_table_index')
    op.drop_index(op.f('ix_schema_table_index_data_source_id'), table_name='schema_table_index')
    op.drop_table('schema_table_index')
    op.drop_index(op.f('ix_schema_column_index_table_name'), table_name='schema_column_index')
    op.drop_index(op.f('ix_schema_column_index_id'), table_name='schema_column_index')
    op.drop_index(op.f('ix_schema_column_index_data_source_id'), table_name='schema_column_index')
    op.drop_index(op.f('ix_schema_column_index_column_name'), table_name='schema_column_index')
    op.drop_table('schema_column_index')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_data_queries_user_id'), table_name='data_queries')
    op.drop_index(op.f('ix_data_queries_id'), table_name='data_queries')
    op.drop_table('data_queries')
    op.drop_table('dashboards')
    op.drop_table('dashboard_templates')
    op.drop_index(op.f('ix_dashboard_charts_id'), table_name='dashboard_charts')
    op.drop_index(op.f('ix_dashboard_charts_dashboard_id'), table_name='dashboard_charts')
    op.drop_index(op.f('ix_dashboard_charts_chart_id'), table_name='dashboard_charts')
    op.drop_table('dashboard_charts')
    # ### end Alembic commands ###