import pytest

from src.modules.data.utils.credentials import encrypt_credentials, decrypt_credentials


def test_encrypt_decrypt_roundtrip(tmp_path, monkeypatch):
    # generate a Fernet key for testing
    from cryptography.fernet import Fernet
    key = Fernet.generate_key().decode()
    monkeypatch.setenv("ENCRYPTION_KEY", key)

    cfg = {"password": "s3cr3t", "api_key": "ak-123"}
    enc = encrypt_credentials(cfg)
    assert enc.get("__enc_password") is True or "password" in enc
    dec = decrypt_credentials(enc)
    assert dec["password"] == "s3cr3t"
    assert dec["api_key"] == "ak-123"


def test_encrypt_raises_without_key_even_in_development(monkeypatch):
    """No plaintext fallback in any environment - dev included.

    Regression guard for the old behavior: ENCRYPTION_KEY unset outside
    production/staging used to log once and silently store credentials in
    plaintext. Local dev now gets a key auto-generated by entrypoint.sh /
    the dev compose files instead - the library itself never degrades.
    """
    monkeypatch.delenv("ENCRYPTION_KEY", raising=False)
    monkeypatch.setenv("ENVIRONMENT", "development")

    with pytest.raises(RuntimeError, match="ENCRYPTION_KEY"):
        encrypt_credentials({"password": "s3cr3t"})


def test_decrypt_raises_without_key(monkeypatch):
    monkeypatch.delenv("ENCRYPTION_KEY", raising=False)
    monkeypatch.setenv("ENVIRONMENT", "development")

    with pytest.raises(RuntimeError, match="ENCRYPTION_KEY"):
        decrypt_credentials({"password": "gAAAAA...", "__enc_password": True})


def test_encrypt_raises_on_malformed_key(monkeypatch):
    monkeypatch.setenv("ENCRYPTION_KEY", "not-a-valid-fernet-key")

    with pytest.raises(RuntimeError, match="invalid"):
        encrypt_credentials({"password": "s3cr3t"})


def test_non_dict_config_passes_through_without_requiring_a_key(monkeypatch):
    """No sensitive fields to protect - _get_fernet() should never be reached."""
    monkeypatch.delenv("ENCRYPTION_KEY", raising=False)
    assert encrypt_credentials("not-a-dict") == "not-a-dict"
    assert decrypt_credentials(None) is None

